export const SET_POSTS = 'POSTS/LOAD_POSTS';
export const SET_COMMENTS = 'COMMENTS/LOAD_COMMENTS';
export const REMOVE_POST = 'POSTS/REMOVE_POST';
export const ADD_POST = 'POSTS/ADD_POST';
export const UPDATE_POST = 'POSTS/UPDATE_POST';
export const UPDATE_COMMENTS = 'POSTS/UPDATE_COMMENTS';
